server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/museumworker?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    driver: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /
      suffix: .jsp
mybatis:
  type-aliases-package: com.example.workers.dao
  mapper-locations: classpath:mapper/*.xml
logging:
  file:
    name: log/log.log
  level:
    root: info
    dao: debug
    pojo: debug
    service: debug
    controller: debug

