package com.example.workers.pojo;

public class Bookings {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.booking_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer bookingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.venue_name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String venueName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.venue_type
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String venueType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.booking_time
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String bookingTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.booking_contest
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String bookingContest;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.worker_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.user_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.audit_state
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String auditState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.audit_content
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String auditContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bookings.venue_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer venueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.booking_id
     *
     * @return the value of bookings.booking_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getBookingId() {
        return bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.booking_id
     *
     * @param bookingId the value for bookings.booking_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setBookingId(Integer bookingId) {
        this.bookingId = bookingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.venue_name
     *
     * @return the value of bookings.venue_name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getVenueName() {
        return venueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.venue_name
     *
     * @param venueName the value for bookings.venue_name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setVenueName(String venueName) {
        this.venueName = venueName == null ? null : venueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.venue_type
     *
     * @return the value of bookings.venue_type
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getVenueType() {
        return venueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.venue_type
     *
     * @param venueType the value for bookings.venue_type
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setVenueType(String venueType) {
        this.venueType = venueType == null ? null : venueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.booking_time
     *
     * @return the value of bookings.booking_time
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getBookingTime() {
        return bookingTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.booking_time
     *
     * @param bookingTime the value for bookings.booking_time
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setBookingTime(String bookingTime) {
        this.bookingTime = bookingTime == null ? null : bookingTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.booking_contest
     *
     * @return the value of bookings.booking_contest
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getBookingContest() {
        return bookingContest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.booking_contest
     *
     * @param bookingContest the value for bookings.booking_contest
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setBookingContest(String bookingContest) {
        this.bookingContest = bookingContest == null ? null : bookingContest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.worker_id
     *
     * @return the value of bookings.worker_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.worker_id
     *
     * @param workerId the value for bookings.worker_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.user_id
     *
     * @return the value of bookings.user_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.user_id
     *
     * @param userId the value for bookings.user_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.audit_state
     *
     * @return the value of bookings.audit_state
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getAuditState() {
        return auditState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.audit_state
     *
     * @param auditState the value for bookings.audit_state
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setAuditState(String auditState) {
        this.auditState = auditState == null ? null : auditState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.audit_content
     *
     * @return the value of bookings.audit_content
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getAuditContent() {
        return auditContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.audit_content
     *
     * @param auditContent the value for bookings.audit_content
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setAuditContent(String auditContent) {
        this.auditContent = auditContent == null ? null : auditContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bookings.venue_id
     *
     * @return the value of bookings.venue_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getVenueId() {
        return venueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bookings.venue_id
     *
     * @param venueId the value for bookings.venue_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setVenueId(Integer venueId) {
        this.venueId = venueId;
    }
}