package com.example.workers.pojo;

public class ExhibitsWithBLOBs extends Exhibits {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exhibits.photo
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column exhibits.content
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exhibits.photo
     *
     * @return the value of exhibits.photo
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exhibits.photo
     *
     * @param photo the value for exhibits.photo
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column exhibits.content
     *
     * @return the value of exhibits.content
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column exhibits.content
     *
     * @param content the value for exhibits.content
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}