package com.example.workers.pojo;

public class TimesPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.time_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer timeId;
    private String photo;

    public String getPhoto() {
        return photo;
    }

    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.work_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer workId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.create_time
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.exhibit_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer exhibitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.time_id
     *
     * @return the value of time_plans.time_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getTimeId() {
        return timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.time_id
     *
     * @param timeId the value for time_plans.time_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setTimeId(Integer timeId) {
        this.timeId = timeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.work_id
     *
     * @return the value of time_plans.work_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getWorkId() {
        return workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.work_id
     *
     * @param workId the value for time_plans.work_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setWorkId(Integer workId) {
        this.workId = workId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.name
     *
     * @return the value of time_plans.name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.name
     *
     * @param name the value for time_plans.name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.create_time
     *
     * @return the value of time_plans.create_time
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.create_time
     *
     * @param createTime the value for time_plans.create_time
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.exhibit_id
     *
     * @return the value of time_plans.exhibit_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getExhibitId() {
        return exhibitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.exhibit_id
     *
     * @param exhibitId the value for time_plans.exhibit_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setExhibitId(Integer exhibitId) {
        this.exhibitId = exhibitId;
    }
}