package com.example.workers.pojo;

public class TimesPlanWithBLOBs extends TimesPlan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.photo
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column time_plans.contest
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String contest;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.photo
     *
     * @return the value of time_plans.photo
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.photo
     *
     * @param photo the value for time_plans.photo
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column time_plans.contest
     *
     * @return the value of time_plans.contest
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getContest() {
        return contest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column time_plans.contest
     *
     * @param contest the value for time_plans.contest
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setContest(String contest) {
        this.contest = contest == null ? null : contest.trim();
    }
}