package com.example.workers.pojo;

public class Workers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.worker_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer workerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.sex
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.phone
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.password
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String password;
    private String venue_name;

    public String getVenue_name() {
        return venue_name;
    }

    public void setVenue_name(String venue_name) {
        this.venue_name = venue_name;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.salt
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private Integer salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workers.avatar
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    private String avatar;

    public Workers(Integer workerId, String name, String sex, String phone, String password, Integer salt, String avatar) {
        this.workerId = workerId;
        this.name = name;
        this.sex = sex;
        this.phone = phone;
        this.password = password;
        this.salt = salt;
        this.avatar = avatar;
    }

    public Workers(Integer workerId, String password) {
        this.workerId = workerId;
        this.password = password;
    }

    public Workers() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.worker_id
     *
     * @return the value of workers.worker_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.worker_id
     *
     * @param workerId the value for workers.worker_id
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.name
     *
     * @return the value of workers.name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.name
     *
     * @param name the value for workers.name
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.sex
     *
     * @return the value of workers.sex
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.sex
     *
     * @param sex the value for workers.sex
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.phone
     *
     * @return the value of workers.phone
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.phone
     *
     * @param phone the value for workers.phone
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.password
     *
     * @return the value of workers.password
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.password
     *
     * @param password the value for workers.password
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.salt
     *
     * @return the value of workers.salt
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public Integer getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.salt
     *
     * @param salt the value for workers.salt
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setSalt(Integer salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column workers.avatar
     *
     * @return the value of workers.avatar
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column workers.avatar
     *
     * @param avatar the value for workers.avatar
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }
}