package com.example.workers.dao;

import com.example.workers.pojo.Exhibits;
import com.example.workers.pojo.ExhibitsExample;
import com.example.workers.pojo.ExhibitsWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ExhibitsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    long countByExample(ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int deleteByExample(ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int deleteByPrimaryKey(Integer exhibitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int insert(ExhibitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int insertSelective(ExhibitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    List<ExhibitsWithBLOBs> selectByExampleWithBLOBs(ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    List<Exhibits> selectByExample(ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    ExhibitsWithBLOBs selectByPrimaryKey(Integer exhibitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int updateByExampleSelective(@Param("record") ExhibitsWithBLOBs record, @Param("example") ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") ExhibitsWithBLOBs record, @Param("example") ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int updateByExample(@Param("record") Exhibits record, @Param("example") ExhibitsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int updateByPrimaryKeySelective(ExhibitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(ExhibitsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exhibits
     *
     * @mbg.generated Sat Nov 26 20:35:52 CST 2022
     */
    int updateByPrimaryKey(Exhibits record);
}