package com.example.workers.dao;

import com.example.workers.pojo.TimesPlan;
import com.example.workers.pojo.TimesPlanExample;
import com.example.workers.pojo.TimesPlanWithBLOBs;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface TimesPlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    long countByExample(TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int deleteByExample(TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int deleteByPrimaryKey(Integer timeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int insert(TimesPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int insertSelective(TimesPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    List<TimesPlanWithBLOBs> selectByExampleWithBLOBs(TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    List<TimesPlan> selectByExample(TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    TimesPlanWithBLOBs selectByPrimaryKey(Integer timeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByExampleSelective(@Param("record") TimesPlanWithBLOBs record, @Param("example") TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") TimesPlanWithBLOBs record, @Param("example") TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByExample(@Param("record") TimesPlan record, @Param("example") TimesPlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByPrimaryKeySelective(TimesPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(TimesPlanWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_plans
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByPrimaryKey(TimesPlan record);
}