package com.example.workers.dao;

import com.example.workers.pojo.Workers;
import com.example.workers.pojo.WorkersExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface WorkersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    long countByExample(WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int deleteByExample(WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int deleteByPrimaryKey(Integer workerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int insert(Workers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int insertSelective(Workers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    List<Workers> selectByExampleWithBLOBs(WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    List<Workers> selectByExample(WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    Workers selectByPrimaryKey(Integer workerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByExampleSelective(@Param("record") Workers record, @Param("example") WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByExampleWithBLOBs(@Param("record") Workers record, @Param("example") WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByExample(@Param("record") Workers record, @Param("example") WorkersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByPrimaryKeySelective(Workers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(Workers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table workers
     *
     * @mbg.generated Sat Nov 26 20:24:13 CST 2022
     */
    int updateByPrimaryKey(Workers record);
}